# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"4\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"]\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x10\n\x08last_idx\x18\x03 \x01(\x03\x12\x11\n\tlast_term\x18\x04 \x01(\x03\"6\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x94\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x10\n\x08prev_idx\x18\x03 \x01(\x03\x12\x11\n\tprev_term\x18\x04 \x01(\x03\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\xc5\x01\n\x16InstallSnapshotRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x15\n\rsnap_last_idx\x18\x03 \x01(\x03\x12\x16\n\x0esnap_last_term\x18\x04 \x01(\x03\x12\x30\n\x02kv\x18\x05 \x03(\x0b\x32$.raft.InstallSnapshotRequest.KvEntry\x1a)\n\x07KvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"5\n\x14InstallSnapshotReply\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xdb\x01\n\x04Raft\x12?\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x16.raft.RequestVoteReply\x12\x45\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply\x12K\n\x0fInstallSnapshot\x12\x1c.raft.InstallSnapshotRequest\x1a\x1a.raft.InstallSnapshotReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSTALLSNAPSHOTREQUEST_KVENTRY']._loaded_options = None
  _globals['_INSTALLSNAPSHOTREQUEST_KVENTRY']._serialized_options = b'8\001'
  _globals['_LOGENTRY']._serialized_start=20
  _globals['_LOGENTRY']._serialized_end=72
  _globals['_REQUESTVOTEREQUEST']._serialized_start=74
  _globals['_REQUESTVOTEREQUEST']._serialized_end=167
  _globals['_REQUESTVOTEREPLY']._serialized_start=169
  _globals['_REQUESTVOTEREPLY']._serialized_end=223
  _globals['_APPENDENTRIESREQUEST']._serialized_start=226
  _globals['_APPENDENTRIESREQUEST']._serialized_end=374
  _globals['_APPENDENTRIESREPLY']._serialized_start=376
  _globals['_APPENDENTRIESREPLY']._serialized_end=427
  _globals['_INSTALLSNAPSHOTREQUEST']._serialized_start=430
  _globals['_INSTALLSNAPSHOTREQUEST']._serialized_end=627
  _globals['_INSTALLSNAPSHOTREQUEST_KVENTRY']._serialized_start=586
  _globals['_INSTALLSNAPSHOTREQUEST_KVENTRY']._serialized_end=627
  _globals['_INSTALLSNAPSHOTREPLY']._serialized_start=629
  _globals['_INSTALLSNAPSHOTREPLY']._serialized_end=682
  _globals['_RAFT']._serialized_start=685
  _globals['_RAFT']._serialized_end=904
# @@protoc_insertion_point(module_scope)
